# Suppress R CMD check notes for dplyr column name references
utils::globalVariables(c(
  "user_id",
  "order_id",
  "is_test",
  "problem_id",
  "correct",
  "has_variation",
  "n_resp",
  "is_validate",
  "n_attempts",
  "n_correct",
  "score",
  "any_wrong",
  "ability",
  "a1",
  "d1",
  "d2",
  "predicted"
))
